# Generated by Django 4.2 on 2026-06-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('class_name', models.CharField(default='未填写', max_length=30, verbose_name='所属班级')),
                ('is_seller', models.BooleanField(default=False, verbose_name='是否开通商户权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='商品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.student', verbose_name='发布商户')),
            ],
        ),
    ]
